version: "3"

services:
    webapp:
        image: webapp:0.1
        build: ./webapp
        #container_name: webapp
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7.30
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - TZ=Asia/Shanghai
        volumes:
            - ./bak.sql:/docker-entrypoint-initdb.d/bak.sql

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./webapp/log/nginx:/var/log/nginx
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - webapp
        environment:
            - TZ=Asia/Shanghai
        ports:
            - "8002:80"
