version: "3"

services:
    webapp:
        image: webapp:0.1
        build: ./webapp
        #container_name: webapp
        depends_on:
            - mysql
        volumes:
            - ./webapp:/webapp
    mysql:
        image: mysql:5.7.30
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - TZ=Asia/Shanghai
        volumes:
            - .mysql/webapp.sql:/docker-entrypoint-initdb.d

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/log:/var/log/nginx
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - webapp
        environment:
            - TZ=Asia/Shanghai
        ports:
            - "8002:80"
