FROM centos:7
COPY ./software /root/Downloads/
WORKDIR /root/Downloads
RUN mv CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo \
	&& yum clean all \
	&& yum makecache \
	&& yum install -y iproute vim curl wget tree gcc python3-devel python3-pip python3-wheel \
	&& mv .vimrc /root \
	&& ln -sf /usr/bin/vim /usr/bin/vi \
	&& mkdir /root/.pip \
	&& mv pip.conf /root/.pip/ \
	&& yum clean all \
	&& rm -rf /root/Downloads

RUN python3 -m pip install -U pip \
	&& python3 -m pip install flask uwsgi supervisor

COPY ./flask/supervisord.conf /etc/supervisord.d/supervisord.conf
COPY ./flask/flask.conf /etc/supervisord.d/conf/flask.conf
COPY ./flask/app app
COPY ./flask/run_supervisord.sh ./run_supervisord.sh

#RUN supervisord -c /etc/supervisord.conf 

EXPOSE 5000

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
CMD ["bash", "run_supervisord.sh"]
