version: '2'
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./log:/var/log/nginx
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./conf.d:/etc/nginx/conf.d
            - ./html:/usr/share/nginx/html
        ports:
            - "8002:80"
        environment:
            - NGINX_HOST=mynginx.com
            - NGINX_PORT=80
